name: pluto_grid_export
description: PlutoGridExport converts PlutoGrid's metadata to CSV or PDF. Used with PlutoGrid.
version: 1.0.6
homepage: https://bosskmk.github.io
repository: https://github.com/bosskmk/pluto_grid/tree/master/packages/pluto_grid_export
publish_to: none

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # local development
  # pluto_grid:
  #   path: ../../
  pluto_grid:
    git:
      url: https://github.com/piggerstar/pluto_grid.git
      ref: staging
  csv: ^5.0.1
  pdf: ^3.10.3
  printing: ^5.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
